### ISSUE TITLE
Multi-layer RNN or LSTM

### ISSUE THREAD

**Issue by pefi9** [clementfarabet/lua---nnx#34]
Hi, 
when I try to have any module prior to the RNN or LSTM, I get this error:

/usr/local/share/lua/5.1/nnx/AbstractRecurrent.lua:70: expecting nested tensors or tables. Got nil and nil instead

/usr/local/share/lua/5.1/nnx/AbstractRecurrent.lua:70: in function 'recursiveCopy'
/usr/local/share/lua/5.1/nnx/AbstractRecurrent.lua:132: in function 'updateGradInput'
/usr/local/share/lua/5.1/nn/Sequential.lua:39: in function 'updateGradInput'
/usr/local/share/lua/5.1/nn/Module.lua:30: in function 'backward'

while I`m calling model:backward(input, gradOutput). 
Is it possible to use these layers (RNN a LSTM) in multi-layer architecture?

Thanks Petr

**Comment by nicholas-leonard** [comment]
Yes. Checkout https://github.com/nicholas-leonard/rnn . You can use [Sequencer](https://github.com/nicholas-leonard/rnn#sequencer) to wrap your recurrent and non-recurrent Modules and stack them with the usual nn.Sequential.

**Comment by pefi9** [comment]
Thanks a lot for your promt answer and for the package.
