### ISSUE TITLE
SpatialFovea Upsampling size inconsistent

### ISSUE THREAD

**Issue by jaderberg** [clementfarabet/lua---nnx#4]
When using the SpatialFovea module in non-focussed mode I am getting inconsistent upsampled sizes, resulting in a failure. You can see from below the issue. Am I doing something wrong?

model = nn.Sequential()
fov_module = nn.SpatialFovea{
        nInputPlane = 3,
        ratios = {1, 2},
        preProcessors = {},
        processors = {pyrmodel, pyrmodel:clone()},
        bilinear = true,
        fov = 24,
        sub = 1,
    }
model:add(fov_module)

t7> y = model:forward(x)
/usr/local/share/torch/lua/nnx/SpatialFovea.lua:231: inconsistent tensor size
stack traceback:
    [C]: in function 'copy'
    /usr/local/share/torch/lua/nnx/SpatialFovea.lua:231: in function 'updateOutput'
    /usr/local/share/torch/lua/nn/Sequential.lua:27: in function 'forward'
    [string "y = model:forward(x)"]:1: in main chunk
    [C]: at 0x01066d2400

t7> return fov_module.upsampled
{
  1 : FloatTensor - size: 32x771x1027
  2 : FloatTensor - size: 32x774x1030
}

t7> =x:size()

```
3
```

  768
 1024
[torch.LongStorage of size 3]

**Comment by chrisbregler** [comment]
Hello there, are there any updates of having a CUDA version of SpatialReSampling ( SpatialPyramid )

**Comment by soumith** [comment]
@chrisbregler no. The only upsampling CUDA module is:
https://github.com/torch/cunn/blob/master/SpatialUpSamplingNearest.cu

and the downsampling module (average) is:
https://github.com/torch/cunn/blob/master/SpatialAveragePooling.cu

**Comment by jonathantompson** [comment]
@chrisbregler 

SpatialUpSamplingNearest is the module I use (Arjun wrote it).  I did experiment with fancier UpSampling (bilinear and even at some point lanczos on the CPU) and they made no difference.  If I was to guess...  The network can learn to be band-limited in the previous conv layer to avoid aliasing.

**Comment by nicholas-leonard** [comment]
@jonathantompson The thing is SpatialUpSamplingNearest is that it isn't as powerful as SpatialReSampling as it can only do integer scales and the owidth and oheight cannot be specified. https://github.com/torch/nn/blob/master/SpatialUpSamplingNearest.lua#L22 . I found this to be very limiting for my applications. So what I do is just cast CudaTensors to FloatTensor, pass them through SpatialReSampling, and convert back. The overhead ain't so bad.

**Comment by jonathantompson** [comment]
Fair enough.  I guess it depends on the application.

If Chris is using it for what I think he's using it for, he's probably doing integer up-sampling of a large number of internal conv features (a stack of 256 to 512 features or something), so I think the GPU->CPU->GPU round trip might be too slow.

Out of curiosity, is anyone using the new K80s yet?  Are people seeing big performance gains vs Titan Black?

**Comment by soumith** [comment]
K80 isnt new. It is 2 K40s on a single board with a slower clock and
reduced memory bandwidth per card. (Shows up as 2 separate cards on the
system)
