### ISSUE TITLE
CTCCriterion cannot correctly calculate gradInput in cpu mode

### ISSUE THREAD

**Issue by JesseYang** [clementfarabet/lua---nnx#56]
After calling backward method, the gradInput is always zeros.

In CTCCriterion:updateGradInput method, I modified the following line from:

cpu_ctc(acts:float(), grads:float(), labels, sizes)

to:

grads = grads:float()
cpu_ctc(acts:float(), grads:float(), labels, sizes)

and it seems to work correctly after reinstall

**Comment by nicholas-leonard** [comment]
@SeanNaren Can you look into this?

**Comment by SeanNaren** [comment]
Woops sorry should've seen this post earlier, I've implemented the fix in this PR #57. Thanks!
