### ISSUE TITLE
Code changes not reflected in Documentation

### ISSUE THREAD

**Issue by NightFury13** [clementfarabet/lua---nnx#63]
The codes for CTCCrtierion.lua seem to have changed from the version I was using and now the forward pass expects the user to give the sizes of the input as one of the parameters. (https://github.com/clementfarabet/lua---nnx/blob/master/CTCCriterion.lua#L19)

Originally, this was taken care of automatically and the user only had to give in the inputs and the targets.

The documentation specific as sample code which still follows the same old way of passing inputs and targets and hence doesn't work on the new code, throwing an error for failing the assertion : 'you need to pass the sizes of input as a tensor'.

**Comment by nicholas-leonard** [comment]
@NightFury13 Can you send a Pull Request with updated documentation?

**Comment by NightFury13** [comment]
@nicholas-leonard : cool, I'll try to send you the PR in a couple of days.

**Comment by nicholas-leonard** [comment]
@NightFury13 Thanks!

**Comment by NightFury13** [comment]
@nicholas-leonard : Please review PR https://github.com/clementfarabet/lua---nnx/pull/64 

I've updated the documentation to accommodate the changes to CTCCriterion.lua and also added the parts on obtaining gradients from doing a backward-pass on the criterion.

**Comment by nicholas-leonard** [comment]
@NightFury13 Thanks again for this :)

**Comment by NightFury13** [comment]
@nicholas-leonard Happy to be of help :)
