### ISSUE TITLE
Inference problem of 'SoftMaxTree' module

### ISSUE THREAD

**Issue by waitwaitforget** [clementfarabet/lua---nnx#65]
Hi, there. I have a question about how to do inference by SoftMaxTree module, as the output of this module is the log likelihood of the target. However, in our testing time, we don't know what the target is, we need the exact class that our network predict. How can we get this by SoftMaxTree? Thanks.

**Comment by nicholas-leonard** [comment]
@waitwaitforget There is currently no inference implementation for SoftMaxTree. Sorry. Feel free to implement it yourself and submit a PR though :P
